### ISSUE TITLE
linters failing

### ISSUE THREAD

**Issue by Link-** [mena-devs/slack_data_collector#14]
(master branch) -- linters failing with the following error after merge with PR#12

```
GLOB sdist-make: ~/Projects/mena-devs.slack/slack_data_collector/setup.py
linters inst-nodeps: ~/Projects/mena-devs.slack/slack_data_collector/.tox/dist/slack_collector-0.0.1.zip
linters installed: flake8==2.6.2,flake8-import-order==0.8,mastool==0.1.3,mccabe==0.5.0,pep257==0.7.0,pep8==1.7.0,pycodestyle==2.0.0,pyflakes==1.2.3,pyslack==0.3.0,PyYAML==3.11,requests==2.10.0,slack-collector==0.0.1
linters runtests: PYTHONHASHSEED='3590518203'
linters runtests: commands[0] | flake8
Traceback (most recent call last):
  File ".tox/linters/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "~/Projects/mena-devs.slack/slack_data_collector/.tox/linters/lib/python3.5/site-packages/flake8/main.py", line 36, in main
    report = flake8_style.check_files()
  File "~/Projects/mena-devs.slack/slack_data_collector/.tox/linters/lib/python3.5/site-packages/flake8/engine.py", line 181, in check_files
    return self._retry_serial(self._styleguide.check_files, paths=paths)
  File "~/Projects/mena-devs.slack/slack_data_collector/.tox/linters/lib/python3.5/site-packages/flake8/engine.py", line 172, in _retry_serial
    return func(*args, **kwargs)
  File "~/Projects/mena-devs.slack/slack_data_collector/.tox/linters/lib/python3.5/site-packages/pycodestyle.py", line 1875, in check_files
    self.input_dir(path)
  File "~/Projects/mena-devs.slack/slack_data_collector/.tox/linters/lib/python3.5/site-packages/pycodestyle.py", line 1911, in input_dir
    runner(os.path.join(root, filename))
  File "~/Projects/mena-devs.slack/slack_data_collector/.tox/linters/lib/python3.5/site-packages/flake8/engine.py", line 126, in input_file
    return fchecker.check_all(expected=expected, line_offset=line_offset)
  File "~/Projects/mena-devs.slack/slack_data_collector/.tox/linters/lib/python3.5/site-packages/pycodestyle.py", line 1608, in check_all
    self.check_ast()
  File "~/Projects/mena-devs.slack/slack_data_collector/.tox/linters/lib/python3.5/site-packages/pycodestyle.py", line 1555, in check_ast
    for lineno, offset, text, check in checker.run():
  File "~/Projects/mena-devs.slack/slack_data_collector/.tox/linters/lib/python3.5/site-packages/flake8_import_order/flake8_linter.py", line 52, in run
    for error in self.check_order():
  File "~/Projects/mena-devs.slack/slack_data_collector/.tox/linters/lib/python3.5/site-packages/flake8_import_order/__init__.py", line 289, in check_order
    first_str = build_str(k)
  File "~/Projects/mena-devs.slack/slack_data_collector/.tox/linters/lib/python3.5/site-packages/flake8_import_order/__init__.py", line 283, in build_str
    if level >= 0:
TypeError: unorderable types: NoneType() >= int()
ERROR: InvocationError: '~/Projects/mena-devs.slack/slack_data_collector/.tox/linters/bin/flake8'
py27 inst-nodeps: ~/Projects/mena-devs.slack/slack_data_collector/.tox/dist/slack_collector-0.0.1.zip
py27 installed: nose==1.3.7,pyslack==0.3.0,PyYAML==3.11,requests==2.10.0,slack-collector==0.0.1
py27 runtests: PYTHONHASHSEED='3590518203'
py27 runtests: commands[0] | nosetests
...
----------------------------------------------------------------------
Ran 3 tests in 0.057s

OK
py35 inst-nodeps: ~/Projects/mena-devs.slack/slack_data_collector/.tox/dist/slack_collector-0.0.1.zip
py35 installed: nose==1.3.7,pyslack==0.3.0,PyYAML==3.11,requests==2.10.0,slack-collector==0.0.1
py35 runtests: PYTHONHASHSEED='3590518203'
py35 runtests: commands[0] | nosetests
...
----------------------------------------------------------------------
Ran 3 tests in 0.057s

OK
_______________________________________________________________ summary _______________________________________________________________
ERROR:   linters: commands failed
  py27: commands succeeded
  py35: commands succeeded
```

**Comment by Link-** [comment]
Recreate the env: 
`tox -re linters`

Make sure tox is running on python2
